# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Loki's Reach
email: 77898583+Zer0-Vector@users.noreply.github.com
description: >-
  Sector wiki form location information and rules reference.

# GitHub Pages settings
domain: zer0-vector.github.io
# url: https://zer0-vector.github.io
github_username: Zer0-Vector
repository: Zer0-Vector/lokis-reach-wiki
baseurl: /lokis-reach-wiki

# Plugin settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
theme: jekyll-theme-minimal
show_downloads: false
permalink: pretty
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      regenerate: true
  - scope:
      path: ""
      type: asteroid-belt
    values:
      tags:
        - Point of Interest
        - Asteroid Belt
  - scope:
      path: ""
      type: system
    values:
      tags:
        - Star System
  - scope:
      path: ""
      type: planet
    values:
      tags:
        - Planet
  - scope:
      path: ""
      type: space-station
    values:
      tags:
        - Point of Interest
        - Space Station
  - scope:
      path: ""
      type: district
    values:
      tags:
        - District
  - scope:
      path: ""
      type: rules
    values:
      tags:
        - Rules
  - scope:
      path: ""
      type: species
    values:
      tags:
        - Species

collections:
  system:
    output: true
  planet:
    output: true
  moon:
    output: true
  asteroid-belt:
    output: true
  space-station:
    output: true
  rules:
    output: true
  species:
    output: true
  district:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
