title: Loki's Reach Wiki
email: 77898583+Zer0-Vector@users.noreply.github.com
# description: >-
#   Sector wiki for location information and rules reference.

# GitHub Pages settings
domain: zer0-vector.github.io
# url: https://zer0-vector.github.io
github_username: Zer0-Vector
repository: Zer0-Vector/lokis-reach-wiki
baseurl: /lokis-reach-wiki

# Custom variables
wrapper_id: site-wrapper

# Site file system settings
collections:
  system:
    output: true
  planet:
    output: true
  moon:
    output: true
  asteroid-belt:
    output: true
  space-station:
    output: true
  rules:
    output: true
  species:
    output: true
  district:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      regenerate: true
  - scope:
      path: ""
      type: asteroid-belt
    values:
      tags:
        - Point of Interest
        - Asteroid Belt
  - scope:
      path: ""
      type: system
    values:
      tags:
        - Star System
  - scope:
      path: ""
      type: planet
    values:
      tags:
        - Planet
  - scope:
      path: ""
      type: space-station
    values:
      tags:
        - Point of Interest
        - Space Station
  - scope:
      path: ""
      type: district
    values:
      tags:
        - District
  - scope:
      path: ""
      type: rules
    values:
      tags:
        - Rules
  - scope:
      path: ""
      type: species
    values:
      tags:
        - Species

# Build settings
show_downloads: true
permalink: pretty

# Plugin settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap

# Markdown rendering options
kramdown:
  header_offset: 1 # h1 in *.md will be rendered as h2
  auto_id_stripping: true
  transliterated_header_ids: true

# HTTP Headers
# webrick:
#   headers:

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
